//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryLink.Models.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailsView
    {
        public long BookID { get; set; }
        public string BookName { get; set; }
        public string ISBN { get; set; }
        public string AuthorList { get; set; }
        public string PublisherName { get; set; }
        public decimal Price { get; set; }
        public byte BookRating { get; set; }
        public string CoverImagePath { get; set; }
    }
}
